

let words= [
["爱情", "ài qíng", "romance; love (romantic)"],
["安排", "ān pái", "to arrange; to plan"],
["安全", "ān quán", "safe; secure; safety"],
["按时", "àn shí", "on time; before deadline"],
["按照", "àn zhào", "according to; in accordance with"],
["百分之", "bǎi fēn zhī", "percent; %"],
["棒", "bàng", "excellent; wonderful"],
["包子", "bāo zi", "steamed stuffed bun"],
["保护", "bǎo hù", "to protect"],
["保证", "bǎo zhèng", "to guarantee; to ensure"],
["报名", "bào míng", "to sign up; to register"],
["抱", "bào", "to hold; to hug"],
["抱歉", "bào qiàn", "to feel sorry; to apologize"],
["倍", "bèi", "times [multiplier]"],
["本来", "běn lái", "originally; at first"],
["笨", "bèn", "stupid; foolish"],
["比如", "bǐ rú", "for example"],
["毕业", "bì yè", "to graduate"],
["遍", "biàn", "measure word for actions; all over"],
["标准", "biāo zhǔn", "standard; criterion"],
["表格", "biǎo gé", "form [document]"],
["表示", "biǎo shì", "to express; to show"],
["表演", "biǎo yǎn", "to perform"],
["表扬", "biǎo yáng", "to praise"],
["饼干", "bǐng gān", "biscuit; cookie"],
["并且", "bìng qiě", "and; moreover"],
["博士", "bó shì", "PhD; doctor"],
["不过", "bú guò", "however; only"],
["不得不", "bù dé bù", "have to; can't avoid"],
["不管", "bù guǎn", "no matter"],
["不仅", "bù jǐn", "not only"],
["部分", "bù fèn", "part; section"],
["擦", "cā", "to wipe; to rub"],
["猜", "cāi", "to guess"],
["材料", "cái liào", "material; data"],
["参观", "cān guān", "to visit; to tour"],
["参加", "cān jiā", "to participate; to attend"],
["餐厅", "cān tīng", "restaurant; dining room"],
["草", "cǎo", "grass"],
["厕所", "cè suǒ", "toilet; bathroom"],
["层", "céng", "layer; floor"],
["差不多", "chà bù duō", "almost; nearly"],
["长城", "cháng chéng", "Great Wall"],
["长江", "cháng jiāng", "Yangtze River"],
["尝", "cháng", "to taste"],
["场", "chǎng", "measure word for events"],
["超市", "chāo shì", "supermarket"],
["成功", "chéng gōng", "to succeed"],
["成为", "chéng wéi", "to become"],
["诚实", "chéng shí", "honest"],
["吃惊", "chī jīng", "to be shocked"],
["重新", "chóng xīn", "again; anew"],
["抽烟", "chōu yān", "to smoke"],
["出差", "chū chāi", "to go on a business trip"],
["出发", "chū fā", "to depart"],
["出生", "chū shēng", "to be born"],
["传真", "chuán zhēn", "fax"],
["窗户", "chuāng hu", "window"],
["词典", "cí diǎn", "dictionary"],
["从来", "cóng lái", "always; never [with negative]"],
["粗心", "cū xīn", "careless"],
["存", "cún", "to save; to deposit"],
["错误", "cuò wù", "mistake; error"],
["答案", "dá àn", "answer; solution"],
["打扮", "dǎ bàn", "to dress up"],
["打扰", "dǎ rǎo", "to disturb"],
["打印", "dǎ yìn", "to print"],
["打招呼", "dǎ zhāo hu", "to greet"],
["打折", "dǎ zhé", "to give a discount"],
["打针", "dǎ zhēn", "to get an injection"],
["大概", "dà gài", "probably; approximately"],
["大使馆", "dà shǐ guǎn", "embassy"],
["大约", "dà yuē", "about; approximately"],
["戴", "dài", "to wear [accessories]"],
["代表", "dài biǎo", "representative"],
["大夫", "dài fu", "doctor"],
["当", "dāng", "to be; to serve as"],
["当时", "dāng shí", "at that time"],
["刀", "dāo", "knife"],
["导游", "dǎo yóu", "tour guide"],
["到处", "dào chù", "everywhere"],
["到底", "dào dǐ", "in the end"],
["道歉", "dào qiàn", "to apologize"],
["得意", "dé yì", "proud; pleased"],
["登机牌", "dēng jī pái", "boarding pass"],
["等", "děng", "etc.; to wait"],
["底", "dǐ", "bottom"],
["地球", "dì qiú", "Earth"],
["地址", "dì zhǐ", "address"],
["掉", "diào", "to drop; to fall"],
["调查", "diào chá", "to investigate"],
["丢", "diū", "to lose"],
["动作", "dòng zuò", "movement; action"],
["堵车", "dǔ chē", "traffic jam"],
["肚子", "dù zi", "belly; stomach"],
["短信", "duǎn xìn", "text message"],
["对话", "duì huà", "dialogue"],
["对面", "duì miàn", "opposite side"],
["儿童", "ér tóng", "children"],
["而", "ér", "and; yet; but"],
["发生", "fā shēng", "to happen; to occur"],
["发展", "fā zhǎn", "to develop"],
["法律", "fǎ lǜ", "law"],
["翻译", "fān yì", "to translate; translator"],
["烦恼", "fán nǎo", "annoyed; trouble"],
["反对", "fǎn duì", "to oppose"],
["方法", "fāng fǎ", "method; way"],
["方面", "fāng miàn", "aspect; side"],
["方面", "fāng miàn", "aspect; respect"],
["房东", "fáng dōng", "landlord"],
["放弃", "fàng qì", "to give up"],
["放暑假", "fàng shǔ jià", "to have summer vacation"],
["放松", "fàng sōng", "to relax"],
["费用", "fèi yòng", "cost; expense"],
["份", "fèn", "portion; share"],
["丰富", "fēng fù", "rich; abundant"],
["否则", "fǒu zé", "otherwise"],
["符合", "fú hé", "to conform to"],
["负责", "fù zé", "to be responsible for"],
["复印", "fù yìn", "to photocopy"],
["复杂", "fù zá", "complicated; complex"],
["付款", "fù kuǎn", "to pay"],
["附近", "fù jìn", "nearby"],
["父亲", "fù qīn", "father"],
["改变", "gǎi biàn", "to change"],
["干杯", "gān bēi", "cheers!"],
["感动", "gǎn dòng", "to move emotionally"],
["感觉", "gǎn jué", "feeling"],
["感情", "gǎn qíng", "emotion; relationship"],
["感谢", "gǎn xiè", "to thank"],
["干", "gàn", "to do; to work"],
["刚", "gāng", "just"],
["高级", "gāo jí", "high level"],
["高速公路", "gāo sù gōng lù", "highway"],
["个子", "gè zi", "height"],
["各", "gè", "each; every"],
["公里", "gōng lǐ", "kilometer"],
["工具", "gōng jù", "tool"],
["工资", "gōng zī", "salary"],
["共同", "gòng tóng", "common; shared"],
["购物", "gòu wù", "shopping"],
["够", "gòu", "enough"],
["估计", "gū jì", "to estimate"],
["鼓励", "gǔ lì", "to encourage"],
["故意", "gù yì", "on purpose"],
["顾客", "gù kè", "customer"],
["挂", "guà", "to hang"],
["关键", "guān jiàn", "key; crucial"],
["观众", "guān zhòng", "audience"],
["管理", "guǎn lǐ", "to manage"],
["光", "guāng", "light; only"],
["广播", "guǎng bò", "broadcast"],
["广告", "guǎng gào", "advertisement"],
["规定", "guī dìng", "rule; regulation"],
["国际", "guó jì", "international"],
["国籍", "guó jí", "nationality"],
["果汁", "guǒ zhī", "fruit juice"],
["过程", "guò chéng", "process"],
["海洋", "hǎi yáng", "ocean"],
["害羞", "hài xiū", "shy"],
["寒假", "hán jià", "winter vacation"],
["汗", "hàn", "sweat"],
["好处", "hǎo chù", "benefit; advantage"],
["好像", "hǎo xiàng", "seem; like"],
["号码", "hào mǎ", "number"],
["合格", "hé gé", "qualified"],
["合适", "hé shì", "suitable"],
["盒子", "hé zi", "box"],
["后悔", "hòu huǐ", "to regret"],
["后来", "hòu lái", "afterward"],
["互相", "hù xiāng", "mutually"],
["护士", "hù shi", "nurse"],
["护照", "hù zhào", "passport"],
["怀疑", "huái yí", "to doubt; suspect"],
["回忆", "huí yì", "memory; to recall"],
["活动", "huó dòng", "activity"],
["活泼", "huó po", "lively"],
["火", "huǒ", "fire"],
["获得", "huò dé", "to obtain"],
["积极", "jī jí", "positive; active"],
["积累", "jī lěi", "to accumulate"],
["基础", "jī chǔ", "foundation"],
["激动", "jī dòng", "excited"],
["计划", "jì huà", "plan"],
["记者", "jì zhě", "journalist"],
["技术", "jì shù", "technology; technique"],
["既然", "jì rán", "since; now that"],
["继续", "jì xù", "to continue"],
["寄", "jì", "to mail"],
["加班", "jiā bān", "to work overtime"],
["加油站", "jiā yóu zhàn", "gas station"],
["家具", "jiā jù", "furniture"],
["价格", "jià gé", "price"],
["坚持", "jiān chí", "to persist"],
["减肥", "jiǎn féi", "to lose weight"],
["减少", "jiǎn shǎo", "to decrease"],
["建议", "jiàn yì", "suggestion; to suggest"],
["将来", "jiāng lái", "future"],
["奖金", "jiǎng jīn", "bonus; award"],
["降低", "jiàng dī", "to reduce"],
["交流", "jiāo liú", "exchange; communication"],
["交通", "jiāo tōng", "traffic"],
["骄傲", "jiāo ào", "proud"],
["饺子", "jiǎo zi", "dumpling"],
["教育", "jiào yù", "education"],
["接受", "jiē shòu", "to accept"],
["接着", "jiē zhe", "to continue"],
["节约", "jié yuē", "to save"],
["结果", "jié guǒ", "result"],
["解释", "jiě shì", "to explain"],
["尽管", "jǐn guǎn", "even though"],
["紧张", "jǐn zhāng", "nervous"],
["进行", "jìn xíng", "to carry out"],
["禁止", "jìn zhǐ", "to prohibit"],
["京剧", "jīng jù", "Beijing opera"],
["经济", "jīng jì", "economy"], ["经历", "jīng lì", "experience; to go through"],
["经验", "jīng yàn", "experience"],
["精彩", "jīng cǎi", "wonderful; splendid"],
["景色", "jǐng sè", "scenery"],
["警察", "jǐng chá", "police officer"],
["竞争", "jìng zhēng", "to compete"],
["镜子", "jìng zi", "mirror"],
["究竟", "jiū jìng", "exactly; after all"],
["举办", "jǔ bàn", "to hold [an event]"],
["举行", "jǔ xíng", "to conduct; to hold"],
["拒绝", "jù jué", "to refuse"],
["距离", "jù lí", "distance"],
["开玩笑", "kāi wán xiào", "to joke"],
["看法", "kàn fǎ", "opinion; view"],
["考虑", "kǎo lǜ", "to consider"],
["科学", "kē xué", "science"],
["咳嗽", "ké sou", "to cough"],
["可怜", "kě lián", "pitiful; poor"],
["可惜", "kě xī", "unfortunately; it's a pity"],
["客厅", "kè tīng", "living room"],
["肯定", "kěn dìng", "definitely; surely"],
["空气", "kōng qì", "air"],
["恐怕", "kǒng pà", "I'm afraid that..."],
["苦", "kǔ", "bitter"],
["矿泉水", "kuàng quán shuǐ", "mineral water"],
["垃圾桶", "lā jī tǒng", "trash can"],
["拉", "lā", "to pull"],
["辣", "là", "spicy"],
["来不及", "lái bu jí", "too late"],
["来得及", "lái de jí", "still have time"],
["懒", "lǎn", "lazy"],
["浪费", "làng fèi", "to waste"],
["浪漫", "làng màn", "romantic"],
["老虎", "lǎo hǔ", "tiger"],
["冷静", "lěng jìng", "calm; cool-headed"],
["离婚", "lí hūn", "to divorce"],
["礼拜天", "lǐ bài tiān", "Sunday"],
["理发", "lǐ fà", "to get a haircut"],
["理解", "lǐ jiě", "to understand"],
["理想", "lǐ xiǎng", "ideal"],
["礼貌", "lǐ mào", "politeness"],
["力气", "lì qi", "strength"],
["俩", "liǎ", "two [people]"],
["联系", "lián xì", "to contact"],
["凉快", "liáng kuai", "cool [weather]"],
["聊天", "liáo tiān", "to chat"],
["留", "liú", "to stay; to remain"],
["留学", "liú xué", "to study abroad"],
["流利", "liú lì", "fluent"],
["流行", "liú xíng", "popular"],
["乱", "luàn", "messy; chaotic"],
["律师", "lǜ shī", "lawyer"],
["麻烦", "má fán", "trouble; troublesome"],
["马虎", "mǎ hu", "careless"],
["麻雀", "má què", "sparrow"],
["毛巾", "máo jīn", "towel"],
["美丽", "měi lì", "beautiful"],
["梦想", "mèng xiǎng", "dream"],
["密码", "mì mǎ", "password"],
["免费", "miǎn fèi", "free of charge"],
["民族", "mín zú", "ethnic group; nationality"],
["母亲", "mǔ qīn", "mother"],
["目的", "mù dì", "goal; purpose"],
["耐心", "nài xīn", "patience"],
["难道", "nán dào", "could it be that...?"],
["难受", "nán shòu", "uncomfortable"],
["内", "nèi", "inside; within"],
["内容", "nèi róng", "content"],
["能力", "néng lì", "ability"],
["年龄", "nián líng", "age"],
["弄", "nòng", "to do; to make [a mess]"],
["暖和", "nuǎn huo", "warm"],
["偶尔", "ǒu ěr", "occasionally"],
["排队", "pái duì", "to queue"],
["排列", "pái liè", "to arrange"],
["判断", "pàn duàn", "to judge"],
["陪", "péi", "to accompany"],
["批评", "pī píng", "to criticize"],
["皮肤", "pí fū", "skin"],
["脾气", "pí qi", "temperament"],
["篇", "piān", "measure word for articles"],
["骗", "piàn", "to deceive; to trick"],
["平时", "píng shí", "normally; usually"],
["瓶子", "píng zi", "bottle"],
["葡萄", "pú tao", "grape"],
["普通话", "pǔ tōng huà", "Mandarin"],
["其次", "qí cì", "secondly"],
["其中", "qí zhōng", "among them"],
["起飞", "qǐ fēi", "to take off"],
["气候", "qì hòu", "climate"],
["千", "qiān", "thousand"],
["签证", "qiān zhèng", "visa"],
["强调", "qiáng diào", "to emphasize"],
["墙", "qiáng", "wall"],
["敲", "qiāo", "to knock"],
["桥", "qiáo", "bridge"],
["巧克力", "qiǎo kè lì", "chocolate"],
["亲戚", "qīn qi", "relative"],
["轻", "qīng", "light [in weight]"],
["轻松", "qīng sōng", "relaxed; easygoing"],
["情况", "qíng kuàng", "situation"],
["请假", "qǐng jià", "ask for time off"],
["全部", "quán bù", "entire; whole"],
["缺点", "quē diǎn", "shortcoming; weakness"],
["缺少", "quē shǎo", "to lack"],
["却", "què", "but; yet"],
["确实", "què shí", "indeed; really"],
["然而", "rán ér", "however"],
["热闹", "rè nao", "lively; bustling"],
["任何", "rèn hé", "any"],
["任务", "rèn wu", "task; assignment"],
["扔", "rēng", "to throw"],
["仍然", "réng rán", "still; yet"],
["日记", "rì jì", "diary"],
["入口", "rù kǒu", "entrance"],
["散步", "sàn bù", "to take a walk"],
["森林", "sēn lín", "forest"],
["沙发", "shā fā", "sofa"],
["伤心", "shāng xīn", "sad; broken-hearted"],
["商量", "shāng liang", "to discuss"],
["稍微", "shāo wēi", "a little bit"],
["社会", "shè huì", "society"],
["申请", "shēn qǐng", "to apply"],
["生活", "shēng huó", "life"],
["生命", "shēng mìng", "life [biological]"],
["生意", "shēng yi", "business"],
["省", "shěng", "province; to save"],
["剩", "shèng", "to remain; to be left over"],
["失望", "shī wàng", "disappointed"],
["师傅", "shī fu", "master; skilled worker"],
["实际", "shí jì", "reality; actual"],
["实在", "shí zài", "indeed; really"],
["使用", "shǐ yòng", "to use"],
["世纪", "shì jì", "century"],
["是否", "shì fǒu", "whether or not"],
["适合", "shì hé", "to suit"],
["适应", "shì yìng", "to adapt to"],
["试", "shì", "to try"],
["收", "shōu", "to receive; to collect"],
["收入", "shōu rù", "income"],
["收拾", "shōu shi", "to tidy up"],
["首都", "shǒu dū", "capital [city]"],
["首先", "shǒu xiān", "first of all"],
["受不了", "shòu bu liǎo", "can't stand it"],
["受到", "shòu dào", "to receive [e.g. attention]"],
["售货员", "shòu huò yuán", "salesperson"],
["输", "shū", "to lose [a game]"],
["熟悉", "shú xī", "to be familiar with"],
["数量", "shù liàng", "quantity"],
["数字", "shù zì", "number; digit"],
["顺便", "shùn biàn", "conveniently; while at it"],
["顺利", "shùn lì", "smooth; without a hitch"],
["说明", "shuō míng", "to explain; explanation"],
["硕士", "shuò shì", "master’s degree"],
["死", "sǐ", "to die"],
["速度", "sù dù", "speed"],
["塑料袋", "sù liào dài", "plastic bag"],
["酸", "suān", "sour"],
["随便", "suí biàn", "whatever; casual"],
["随着", "suí zhe", "along with"],
["孙子", "sūn zi", "grandson"],
["所有", "suǒ yǒu", "all; every"],
["台", "tái", "platform; measure word for machines"],
["抬", "tái", "to lift; to raise"],
["谈", "tán", "to talk"],
["汤", "tāng", "soup"],
["糖", "táng", "sugar; candy"],
["躺", "tǎng", "to lie down"],
["趟", "tàng", "measure word for trips"],
["讨论", "tǎo lùn", "to discuss"],
["讨厌", "tǎo yàn", "to dislike; annoying"],
["特别", "tè bié", "especially"],
["特点", "tè diǎn", "characteristic"],
["提高", "tí gāo", "to improve"],
["提供", "tí gōng", "to provide"],
["提前", "tí qián", "in advance"],
["提醒", "tí xǐng", "to remind"],
["填空", "tián kòng", "to fill in the blanks"],
["条件", "tiáo jiàn", "condition; requirement"],
["停止", "tíng zhǐ", "to stop"],
["挺", "tǐng", "very; quite"],
["通过", "tōng guò", "through; to pass"],
["通知", "tōng zhī", "to inform; notice"],
["同情", "tóng qíng", "to sympathize"],
["同时", "tóng shí", "at the same time"],
["推", "tuī", "to push"],
["推迟", "tuī chí", "to postpone"],
["脱", "tuō", "to take off [clothes]"],
["袜子", "wà zi", "socks"],
["完全", "wán quán", "completely"],
["玩具", "wán jù", "toy"],
["碗", "wǎn", "bowl"],
["万", "wàn", "ten thousand"],
["往往", "wǎng wǎng", "often"],
["网站", "wǎng zhàn", "website"],
["危险", "wēi xiǎn", "dangerous"],
["卫生间", "wèi shēng jiān", "restroom"],
["味道", "wèi dào", "taste; flavor"],
["温度", "wēn dù", "temperature"],
["文章", "wén zhāng", "article; essay"],
["污染", "wū rǎn", "pollution"],
["无聊", "wú liáo", "boring"],
["无论", "wú lùn", "regardless"],
["误会", "wù huì", "to misunderstand"],
["西红柿", "xī hóng shì", "tomato"],
["吸引", "xī yǐn", "to attract"],
["习惯", "xí guàn", "habit; to be used to"],
["洗衣机", "xǐ yī jī", "washing machine"],
["现金", "xiàn jīn", "cash"],
["羡慕", "xiàn mù", "to envy"],
["相反", "xiāng fǎn", "on the contrary"],
["相同", "xiāng tóng", "same"],
["详细", "xiáng xì", "detailed"],
["响", "xiǎng", "to make a sound"],
["橡皮", "xiàng pí", "eraser"],
["消息", "xiāo xi", "news; information"],
["小吃", "xiǎo chī", "snack; street food"],
["小伙子", "xiǎo huǒ zi", "young man"],
["小说", "xiǎo shuō", "novel"],
["小心", "xiǎo xīn", "to be careful"],
["效果", "xiào guǒ", "effect; result"],
["笑话", "xiào hua", "joke"],
["心情", "xīn qíng", "mood"],
["辛苦", "xīn kǔ", "hard; exhausting"],
["信任", "xìn rèn", "to trust"],
["信心", "xìn xīn", "confidence"],
["兴奋", "xīng fèn", "excited"],
["行", "xíng", "OK; capable"],
["醒", "xǐng", "to wake up"],
["幸福", "xìng fú", "happiness"],
["性别", "xìng bié", "gender"],
["性格", "xìng gé", "personality"],
["修理", "xiū lǐ", "to repair"],
["许多", "xǔ duō", "many; a lot of"],
["压力", "yā lì", "pressure"],
["牙膏", "yá gāo", "toothpaste"],
["亚洲", "Yà zhōu", "Asia"],
["盐", "yán", "salt"],
["严格", "yán gé", "strict"],
["严重", "yán zhòng", "serious"],
["研究", "yán jiū", "to research; research"],
["演出", "yǎn chū", "performance; to perform"],
["演员", "yǎn yuán", "actor; actress"],
["眼镜", "yǎn jìng", "glasses"],
["阳光", "yáng guāng", "sunlight"],
["养成", "yǎng chéng", "to develop [a habit]"],
["样子", "yàng zi", "appearance"],
["邀请", "yāo qǐng", "to invite"],
["要是", "yào shi", "if"],
["钥匙", "yào shi", "key"],
["也许", "yě xǔ", "perhaps; maybe"],
["页", "yè", "page"],
["叶子", "yè zi", "leaf"],
["一切", "yí qiè", "everything"],
["以", "yǐ", "by means of"],
["以为", "yǐ wéi", "to think [mistakenly]"],
["艺术", "yì shù", "art"],
["意见", "yì jiàn", "opinion"],
["因此", "yīn cǐ", "therefore"],
["引起", "yǐn qǐ", "to cause"],
["印象", "yìn xiàng", "impression"],
["赢", "yíng", "to win"],
["应聘", "yìng pìn", "to apply for a job"],
["永远", "yǒng yuǎn", "forever"],
["勇敢", "yǒng gǎn", "brave"],
["幽默", "yōu mò", "humorous"],
["优点", "yōu diǎn", "merit; advantage"],
["优秀", "yōu xiù", "excellent"],
["优雅", "yōu yǎ", "graceful"],
["尤其", "yóu qí", "especially"],
["由", "yóu", "by [indicates agent]"],
["由于", "yóu yú", "because"],
["邮局", "yóu jú", "post office"],
["游览", "yóu lǎn", "to tour; sightseeing"],
["友好", "yǒu hǎo", "friendly"],
["友谊", "yǒu yì", "friendship"],
["有趣", "yǒu qù", "interesting"],
["于是", "yú shì", "so; therefore"],
["愉快", "yú kuài", "happy; pleasant"],
["语言", "yǔ yán", "language"],
["宇宙", "yǔ zhòu", "universe"],
["遇到", "yù dào", "to come across"],
["预习", "yù xí", "to preview"],
["元", "yuán", "Yuan [currency]"],
["原来", "yuán lái", "originally; as it turns out"],
["原因", "yuán yīn", "reason"],
["约会", "yuē huì", "appointment; date"],
["阅读", "yuè dú", "to read"],
["允许", "yǔn xǔ", "to allow; to permit"],
["杂志", "zá zhì", "magazine"],
["咱们", "zán men", "we; us"],
["暂时", "zàn shí", "temporary"],
["脏", "zāng", "dirty"],
["责任", "zé rèn", "responsibility"],
["增加", "zēng jiā", "to increase"],
["增高", "zēng gāo", "to raise"],
["占线", "zhàn xiàn", "the line is busy"],
["招聘", "zhāo pìn", "to recruit"],
["着急", "zháo jí", "to worry"],
["正式", "zhèng shì", "formal"],
["证明", "zhèng míng", "to prove"],
["整理", "zhěng lǐ", "to tidy up"],
["正常", "zhèng cháng", "normal"],
["正确", "zhèng què", "correct"],
["正式", "zhèng shì", "formal; official"],
["支持", "zhī chí", "to support"],
["知识", "zhī shi", "knowledge"],
["值得", "zhí dé", "to be worth"],
["职业", "zhí yè", "profession"],
["直接", "zhí jiē", "direct"],
["植物", "zhí wù", "plant"],
["只好", "zhǐ hǎo", "have no choice but to"],
["只要", "zhǐ yào", "so long as"],
["指", "zhǐ", "to point at; to refer to"],
["质量", "zhì liàng", "quality"],
["至少", "zhì shǎo", "at least"],
["重视", "zhòng shì", "to attach importance to"],
["祝贺", "zhù hè", "to congratulate"],
["著名", "zhù míng", "famous"],
["专门", "zhuān mén", "specialized"],
["专业", "zhuān yè", "major; specialty"],
["准确", "zhǔn què", "accurate"],
["准时", "zhǔn shí", "on time"],
["仔细", "zǐ xì", "careful"],
["自然", "zì rán", "nature; natural"],
["自由", "zì yóu", "freedom"],
["总是", "zǒng shì", "always"],
["总结", "zǒng jié", "to summarize"],
["最好", "zuì hǎo", "had better"],
["最后", "zuì hòu", "last; finally"],
["最近", "zuì jìn", "recently"],
["尊重", "zūn zhòng", "to respect"],
["左右", "zuǒ yòu", "about; approximately"],
["作家", "zuò jiā", "writer"],
["作用", "zuò yòng", "effect; function"],
["作者", "zuò zhě", "author"],
["座位", "zuò wèi", "seat"],
["座", "zuò", "measure word for buildings, mountains"],
["做生意", "zuò shēng yi", "to do business"],
["责任感", "zé rèn gǎn", "sense of responsibility"],
["自信", "zì xìn", "self-confidence"],
["资源", "zī yuán", "resources"],
["遵守", "zūn shǒu", "to comply with; to obey"],
["总结经验", "zǒng jié jīng yàn", "to sum up experience"],
["作出贡献", "zuò chū gòng xiàn", "to make a contribution"],
["自觉", "zì jué", "self-aware; consciously"],
["增强", "zēng qiáng", "to strengthen; to enhance"],
["自我介绍", "zì wǒ jiè shào", "self-introduction"],
["自尊", "zì zūn", "self-esteem"],
["自动", "zì dòng", "automatic"],
["组织", "zǔ zhī", "to organize; organization"],
["走路", "zǒu lù", "to walk"],
["足球", "zú qiú", "football; soccer"],
["作业", "zuò yè", "homework"],
["总结教训", "zǒng jié jiào xùn", "to sum up lessons learned"],
["最好笑", "zuì hǎo xiào", "funniest"],
["最新", "zuì xīn", "latest"],
["自卑", "zì bēi", "inferiority"],
["自律", "zì lǜ", "self-discipline"],
["最少", "zuì shǎo", "at least"],
["最初", "zuì chū", "at first; initially"],
["最终", "zuì zhōng", "eventually"],
["作风", "zuò fēng", "style of work"],
["做主", "zuò zhǔ", "to make the decision"],
["自满", "zì mǎn", "complacent"],
["足够", "zú gòu", "enough; sufficient"],
["总结规律", "zǒng jié guī lǜ", "to summarize patterns"],
["自救", "zì jiù", "self-rescue"],
["综合", "zōng hé", "comprehensive"],
["组合", "zǔ hé", "to combine; combination"],
["阻止", "zǔ zhǐ", "to prevent"],
["走遍", "zǒu biàn", "to travel all over"],
["自从", "zì cóng", "since"],
["作证", "zuò zhèng", "to testify"],
["尊严", "zūn yán", "dignity"],
["资金", "zī jīn", "funds"],
["资料", "zī liào", "data; material"],
["自杀", "zì shā", "to commit suicide"],
["自我", "zì wǒ", "self"],
["综合能力", "zōng hé néng lì", "comprehensive ability"],
["自私", "zì sī", "selfish"],
["足以", "zú yǐ", "enough to..."],
["做工", "zuò gōng", "craftsmanship; workmanship"],
["租金", "zū jīn", "rent [money]"],
["作证人", "zuò zhèng rén", "witness"],
["阻碍", "zǔ ài", "to hinder; obstacle"],
["罪犯", "zuì fàn", "criminal"],
["最后通牒", "zuì hòu tōng dié", "final ultimatum"],
["自主", "zì zhǔ", "autonomous; independent"],
["综合症", "zōng hé zhèng", "syndrome"],
["走向", "zǒu xiàng", "trend; direction"],
["阻力", "zǔ lì", "resistance"],
["组织者", "zǔ zhī zhě", "organizer"],
["作案", "zuò àn", "to commit a crime"],
["罪行", "zuì xíng", "crime"],
["作恶", "zuò è", "to do evil"],
["作弊", "zuò bì", "to cheat"],
["作陪", "zuò péi", "to keep company [in formal events]"],
["自恋", "zì liàn", "narcissistic"],
["最初的想法", "zuì chū de xiǎng fǎ", "original idea"],
["左右为难", "zuǒ yòu wéi nán", "in a dilemma"],
["自发", "zì fā", "spontaneous"],
["组装", "zǔ zhuāng", "to assemble"],
["自主创新", "zì zhǔ chuàng xīn", "independent innovation"],
["综艺节目", "zōng yì jié mù", "variety show"],
["最终结果", "zuì zhōng jié guǒ", "final result"],
["走投无路", "zǒu tóu wú lù", "at the end of one’s rope"],
["走马观花", "zǒu mǎ guān huā", "to gain a superficial understanding"],
["自告奋勇", "zì gào fèn yǒng", "to volunteer bravely"],
["自圆其说", "zì yuán qí shuō", "to justify oneself"],
["尊老爱幼", "zūn lǎo ài yòu", "to respect the old and love the young"],
["左右手", "zuǒ yòu shǒu", "right-hand man"],
["坐立不安", "zuò lì bù ān", "restless"],
["走向世界", "zǒu xiàng shì jiè", "to go global"],
["作壁上观", "zuò bì shàng guān", "to be a bystander"],
["自相矛盾", "zì xiāng máo dùn", "self-contradictory"]
]
